# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fincreek.com
title: Fin Creek
email: AndrewKoszela@gmail.com
author: Andrew Koszela
description: Digital Marketing Company

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/AndrewKoszela
  - title: github
    url: https://github.com/AndrewKoszela
  - title: linkedin
    url: 
